# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 900ff6077f47cacc0861c21794517196ccea21c420f55b76d1fa38ce404ce0f521a61c6c2b3f48631ad056292c1b9c706b7c284a08ce8252c47b358dfa4333b2

test:
  secret_key_base: d88a5018c237f2c63ba633adc096a137ec71ba7b3cc825b7f79c93232c8ede78d7ec51e3d2116b04115e5e3c9492531acefc14932e04e11a505bbaba0a8e41d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
